name: main

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for manual build and deploy"
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v4

      - name: Run unit tests
        run: make test
