name: main

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for manual build and deploy"
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.0"

      - name: Initialise env
        run: make init

      - name: Install env
        run: make install

      - name: Generate certs
        run: make gencert

      - name: Install protoc
        uses: arduino/setup-protoc@v3

      - name: Compile protobufs
        run: make compile

      - name: Run unit tests
        run: make test
